### ISSUE TITLE
hex file help

### ISSUE THREAD

**Issue by m00ds** [keyboard-magpie/isopad#1]
Hey there, I'm having trouble with the hex file and flashing the board. To be honest, I have no idea what I'm doing. Could you point me in the direction of any help. Cheers.

**Comment by keyboard-magpie** [comment]
You'll need the latest version of QMK toolbox from here: [https://github.com/qmk/qmk_toolbox/releases](url)

Load my hex file in the top bar. Don't touch any other settings.

With USB plugged in (make sure it's a data cable!!): Reset your controller into bootloader mode (pro micro- short ground and reset twice quickly, elite C and others- short them once)

You should see yellow text appear in the toolbox console; you can then click flash.

As standard, the isopad will act as an enter key; you can use the VIA PC app from here: [https://github.com/the-via/releases/releases/tag/v1.3.1](url) to customise what it does.

If you have any other queries, message me on the mechboards UK discord: [https://discord.gg/sqsDB3z3HB](url)
